INPUT:
  min_size_train: 800
  max_size_train:
  use_255: False
  pixel_mean: (0.406, 0.456, 0.485)
  pixel_std: (0.225, 0.224, 0.229)


TRAIN:
  model: 'retina_resnet50_v1s_coco'
  pretrained_base: '/home/ace/.torch/models/resnet50_v1s.pth'



TEST:
  pretrained: '/home/ace/.torch/models/retina_resnet50_v1b_coco.pth'